#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TERRAFORM_DIR="${REPO_ROOT}/terraform"
TFVARS_FILE="${TERRAFORM_DIR}/terraform.tfvars"

OUTPUT_FILE="${1:-}"

err() {
  echo "ERROR: $*" >&2
}

info() {
  echo "INFO: $*" >&2
}

if ! command -v terraform >/dev/null 2>&1; then
  err "terraform is required but not installed."
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  err "jq is required but not installed. Install it first (e.g. apt install jq or brew install jq)."
  exit 1
fi

if [[ ! -d "${TERRAFORM_DIR}" ]]; then
  err "Terraform directory not found at ${TERRAFORM_DIR}."
  exit 1
fi

if [[ ! -f "${TFVARS_FILE}" ]]; then
  err "${TFVARS_FILE} not found. Create it first (e.g. cp terraform/terraform.tfvars.example terraform/terraform.tfvars)."
  exit 1
fi

if ! terraform -chdir="${TERRAFORM_DIR}" output -json >/dev/null 2>&1; then
  err "Terraform outputs are not available. Run terraform init/apply in terraform/ first."
  exit 1
fi

demo_key_name="$(awk -F= '
  /^[[:space:]]*demo_key_name[[:space:]]*=/ {
    value=$2
    gsub(/^[[:space:]]+|[[:space:]]+$/, "", value)
    gsub(/"/, "", value)
    print value
    exit
  }
' "${TFVARS_FILE}")"

if [[ -z "${demo_key_name}" ]]; then
  err "demo_key_name is empty in terraform.tfvars. Set demo_key_name to your EC2 key pair name."
  exit 1
fi

key_path="${HOME}/.ssh/${demo_key_name}.pem"
if [[ ! -f "${key_path}" ]]; then
  info "Local key file not found at ${key_path}."
  info "Inventory will still be generated. Update ansible_ssh_private_key_file if your key is elsewhere."
fi

mapfile -t ubuntu_ips < <(
  terraform -chdir="${TERRAFORM_DIR}" output -json ubuntu_instance_public_ips \
    | jq -r '.[]? | select(. != null and . != "")'
)

mapfile -t redhat_ips < <(
  terraform -chdir="${TERRAFORM_DIR}" output -json amazon_linux_instance_public_ips \
    | jq -r '.[]? | select(. != null and . != "")'
)

if [[ ${#ubuntu_ips[@]} -eq 0 && ${#redhat_ips[@]} -eq 0 ]]; then
  err "No demo EC2 public IPs found in Terraform outputs."
  err "Enable instances in terraform/terraform.tfvars (ubuntu_instance_count and/or amazon_linux_instance_count) and run terraform apply."
  exit 1
fi

generate_inventory() {
  echo "# Generated by scripts/generate-inventory.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo
  echo "[ubuntu]"
  if [[ ${#ubuntu_ips[@]} -eq 0 ]]; then
    echo "# (none)"
  else
    for i in "${!ubuntu_ips[@]}"; do
      n=$((i + 1))
      echo "ubuntu-${n} ansible_host=${ubuntu_ips[$i]} ansible_user=ubuntu"
    done
  fi

  echo
  echo "[redhat]"
  if [[ ${#redhat_ips[@]} -eq 0 ]]; then
    echo "# (none)"
  else
    for i in "${!redhat_ips[@]}"; do
      n=$((i + 1))
      echo "rhel-${n} ansible_host=${redhat_ips[$i]} ansible_user=ec2-user"
    done
  fi

  echo
  echo "[all:vars]"
  echo "ansible_ssh_private_key_file=~/.ssh/${demo_key_name}.pem"
  echo "ansible_ssh_common_args=-o StrictHostKeyChecking=accept-new -o ConnectTimeout=10"
}

if [[ -n "${OUTPUT_FILE}" ]]; then
  generate_inventory >"${OUTPUT_FILE}"
  info "Inventory written to ${OUTPUT_FILE}"
else
  generate_inventory
fi
